### ISSUE TITLE
feature request - have default limits and requests for namespaceconfig quotas

### ISSUE THREAD

**Issue by gforster** [redhat-cop/namespace-configuration-operator#101]
The NamespaceConfig allows you to set quotas for the Projects, but when deploying a pod that does not specify limits or requests, it fails. I found I was able to set a LimitRange so that there were some default values for limits and requests. Setting the max to the same values as the quotas in the NamespaceConfig seems to have the desired effect.

It would be nice to have that all as part of the operator instead of managing two separate pieces.

Or, maybe I'm missing something/doing it wrong.

**Comment by raffaelespazzoli** [comment]
the approach here is to define both the quota and the limit range (with defaults, not max defined) in the same nameaspace config.

**Comment by raffaelespazzoli** [comment]
may I close this?
