### ISSUE TITLE
Automatic namespace creation doesn't appear to issue roles for user

### ISSUE THREAD

**Issue by utherp0** [redhat-cop/namespace-configuration-operator#107]
Doing a basic demo of the Operator - created a userconfig against the provider with the spec:

      objectTemplate: |
        apiVersion: v1
        kind: Namespace
        metadata:
          name: {{ .Name }}-sandbox

When a user logs in the namespace is created correctly, but the user has no access to it and doesn't see it.

Is this as intended and I'm missing something?

**Comment by denisj07** [comment]
You should add a rolebinding for your user, take a look at the examples: https://github.com/redhat-cop/namespace-configuration-operator/blob/master/examples/user-sandbox/user-config.yaml#L13-L26

**Comment by raffaelespazzoli** [comment]
may I close this?
