### ISSUE TITLE
Can't find the operator on operatorhub.io

### ISSUE THREAD

**Issue by andloh** [redhat-cop/namespace-configuration-operator#109]
Hi, 

Thanks for the work on this operator :D 

I am trying to use it for vanilla k8s, but I can't find it on the operatorhub.io? 
Is this operator ONLY available for openshift/OKD? 

From what I see...it should be available: 

https://github.com/operator-framework/community-operators/tree/master/community-operators/namespace-configuration-operator

> It is recommended to deploy this operator via OperatorHub, but you can also deploy it using Helm.

..also the helm install does not work, the chart does not create a secret object for the operator (but that is another issue )
```bash
Unable to attach or mount volumes: unmounted volumes=[tls-cert]
```

**Comment by raffaelespazzoli** [comment]
helm installation should be used when not running on OpenShift. Can you try helm with the latest version? All issues on the helm chart should have been fixed.

**Comment by raffaelespazzoli** [comment]
may I close this issue?
