### ISSUE TITLE
Best way to deploy ~60 Networkpolicies?

### ISSUE THREAD

**Issue by ichmachnixichgucknur** [redhat-cop/namespace-configuration-operator#122]
Hi,
we are requested to apply approx ~60 configurations (networkPolicies) to ~180 Namespaces (counting).
I created a file for every config and applied this. That works, but the operator takes approx 7GB of RAM.

I thought about optimizing this and to create a single file. On the testsystem, the RAM Usage is much lower and for the first config ist works. But by applying an update everything breaks. The message is:
```ERROR	controller-runtime.manager.controller.namespaceconfig	Reconciler error	{"reconciler group": "redhatcop.redhat.io", "reconciler kind": "NamespaceConfig", "name": "netpol-rules", "namespace": "", "error": "Request entity too large: limit is 3145728"}```
So this does not work.

What is the recommended way to apply such a configuration?

Thx
Ronny

**Comment by raffaelespazzoli** [comment]
the memory consumed by the operator if roughly proportional to the number of namespaceconfig.
Just to understand you have 60 different network policies that need to be applied in different combinations to 180 namespaces?
can you do some consolidation? A namespace config can carry an array of dis-homogeneous objects.

**Comment by ichmachnixichgucknur** [comment]
I have 60 networkpolicies applied to namespaces matching one label (matching 99% of the cluster).
Working with 60 namespaceconfigs works, but ends in a huge memory consumption - as you mentioned proportional to the configs.
I consolidated the config to one namespaceconfig including all the networkpolicies - I think that is what you are talking about. Initially this works, but on an update on the namespaceconfig I get the error I mentioned. So this does not work.

**Comment by raffaelespazzoli** [comment]
got it, I now see what the problem is. probably the status field is so big that the update does not work. let me think what I can do in that space....

**Comment by raffaelespazzoli** [comment]
@cnuland @trevorbox I think the solution we should adopt here is to filter the successful reconcilers from the status and display only the ones that are erroring out. This would drastically reduce the size of the etcd object.
I'm currently busy and cannot work on this, would you be able to make this fix?

**Comment by ichmachnixichgucknur** [comment]
@raffaelespazzoli I will test this and come back to you.
