### ISSUE TITLE
Upgrade to 1.2.3 Fails -  field is immutable

### ISSUE THREAD

**Issue by kylegalea** [redhat-cop/namespace-configuration-operator#128]
@raffaelespazzoli 

Upgrade to 1.2.3 namespace config operator is failing on trying to change an immutable field in the deployment of the operator.

install strategy failed: Deployment.apps "namespace-configuration-operator-controller-manager" is invalid: spec.selector: Invalid value: v1.LabelSelector{MatchLabels:map[string]string{"control-plane":"namespace-configuration-operator"}, MatchExpressions:[]v1.LabelSelectorRequirement(nil)}: field is immutable

We do not wish to manually delete the 1.22 deployment as this might impact the templated objects we have using this operator.

Thanks

**Comment by kylegalea** [comment]
Deleting the deployment works - templated objects were not removed

**Comment by mto-beep** [comment]
![grafik](https://user-images.githubusercontent.com/103566657/163137768-475add84-7401-4e8d-be9b-6d03a2af92cf.png)

Hey i have the same problem, so you deleted the deployment of 1.2.2? and have you enabled "Delete dependent objects of this resource" ?

**Comment by mto-beep** [comment]
Thanks, that worked.
