### ISSUE TITLE
Consolidate namespace-configuration-operator with rbac-permissions-operator?

### ISSUE THREAD

**Issue by jtudelag** [redhat-cop/namespace-configuration-operator#25]
I would be great to merge functionality from `namespace-configuration-operator` and the [rbac-permission-operator](https://github.com/openshift/rbac-permissions-operator)

They both have related features, and IMHO would be good to consolidate both into just one awesome operator ;).

**Comment by raffaelespazzoli** [comment]
the provided link seems to be broken. can you fix it.

**Comment by jtudelag** [comment]
@raffaelespazzoli done ;)

**Comment by raffaelespazzoli** [comment]
I think the namespace-configuration-operator can be used to create permissions.Alternatively the rbac-permission-operator can and the operator could be used together. Either way I don't see what kind of merge you are asking for.
Can I close this issue?

**Comment by jtudelag** [comment]
Yes, I will go ahead and close it, I dont even remember why I opened it in the first place....
