### ISSUE TITLE
Architecture Diagram?

### ISSUE THREAD

**Issue by karlkfi** [redhat-cop/namespace-configuration-operator#26]
Anyone have a component diagram for this? Is it just a single Deployment? Is it HA? 

Side note:
Is this really an operator? Seems like just a controller with a CRD, since it doesn't manage the lifecycle of any pods or application.

**Comment by raffaelespazzoli** [comment]
@karlkfi there is nothing that gets deployed by this operator except for the resources that you define.
this operator manages configuration not applications, so I feel most of your questions do not apply.
