### ISSUE TITLE
Unable to build, could be some version mismatch

### ISSUE THREAD

**Issue by Snakesms** [redhat-cop/namespace-configuration-operator#3]
# github.com/redhat-cop/namespace-configuration-operator/pkg/apis/redhatcop/v1alpha1
..\..\..\..\go\src\github.com\redhat-cop\namespace-configuration-operator\pkg\apis\redhatcop\v1alpha1\register.go:18:19: undefined: scheme.Builder

# github.com/redhat-cop/operator-utils/pkg/util
..\..\..\..\go\src\github.com\redhat-cop\operator-utils\pkg\util\reconciler.go:70:44: cannot use owner (type "k8s.io/apimachinery/pkg/apis/meta/v1".Object) as type "sigs.k8s.io/controller-runtime/vendor/k8s.io/apimachinery/pkg/apis/meta/v1".Object in argument to controllerutil.SetControllerReference:
	"k8s.io/apimachinery/pkg/apis/meta/v1".Object does not implement "sigs.k8s.io/controller-runtime/vendor/k8s.io/apimachinery/pkg/apis/meta/v1".Object (wrong type for GetCreationTimestamp method)
		have GetCreationTimestamp() "k8s.io/apimachinery/pkg/apis/meta/v1".Time
		want GetCreationTimestamp() "sigs.k8s.io/controller-runtime/vendor/k8s.io/apimachinery/pkg/apis/meta/v1".Time
..\..\..\..\go\src\github.com\redhat-cop\operator-utils\pkg\util\reconciler.go:70:44: cannot use obj (type "k8s.io/apimachinery/pkg/apis/meta/v1".Object) as type "sigs.k8s.io/controller-runtime/vendor/k8s.io/apimachinery/pkg/apis/meta/v1".Object in argument to controllerutil.SetControllerReference:
	"k8s.io/apimachinery/pkg/apis/meta/v1".Object does not implement "sigs.k8s.io/controller-runtime/vendor/k8s.io/apimachinery/pkg/apis/meta/v1".Object (wrong type for GetCreationTimestamp method)
		have GetCreationTimestamp() "k8s.io/apimachinery/pkg/apis/meta/v1".Time
		want GetCreationTimestamp() "sigs.k8s.io/controller-runtime/vendor/k8s.io/apimachinery/pkg/apis/meta/v1".Time
..\..\..\..\go\src\github.com\redhat-cop\operator-utils\pkg\util\reconciler.go:70:68: cannot use r.GetScheme() (type *"k8s.io/apimachinery/pkg/runtime".Scheme) as type *"sigs.k8s.io/controller-runtime/vendor/k8s.io/apimachinery/pkg/runtime".Scheme in argument to controllerutil.SetControllerReference
..\..\..\..\go\src\github.com\redhat-cop\operator-utils\pkg\util\reconciler.go:84:63: cannot use "k8s.io/apimachinery/pkg/types".NamespacedName literal (type "k8s.io/apimachinery/pkg/types".NamespacedName) as type "sigs.k8s.io/controller-runtime/vendor/k8s.io/apimachinery/pkg/types".NamespacedName in argument to r.GetClient().Get
..\..\..\..\go\src\github.com\redhat-cop\operator-utils\pkg\util\reconciler.go:87:5: cannot use &obj2 (type *unstructured.Unstructured) as type "sigs.k8s.io/controller-runtime/vendor/k8s.io/apimachinery/pkg/runtime".Object in argument to r.GetClient().Get:
	*unstructured.Unstructured does not implement "sigs.k8s.io/controller-runtime/vendor/k8s.io/apimachinery/pkg/runtime".Object (wrong type for DeepCopyObject method)
		have DeepCopyObject() "k8s.io/apimachinery/pkg/runtime".Object
		want DeepCopyObject() "sigs.k8s.io/controller-runtime/vendor/k8s.io/apimachinery/pkg/runtime".Object
..\..\..\..\go\src\github.com\redhat-cop\operator-utils\pkg\util\reconciler.go:90:42: cannot use runtimeObj (type "k8s.io/apimachinery/pkg/runtime".Object) as type "sigs.k8s.io/controller-runtime/vendor/k8s.io/apimachinery/pkg/runtime".Object in argument to r.GetClient().Create:
	"k8s.io/apimachinery/pkg/runtime".Object does not implement "sigs.k8s.io/controller-runtime/vendor/k8s.io/apimachinery/pkg/runtime".Object (wrong type for DeepCopyObject method)
		have DeepCopyObject() "k8s.io/apimachinery/pkg/runtime".Object
		want DeepCopyObject() "sigs.k8s.io/controller-runtime/vendor/k8s.io/apimachinery/pkg/runtime".Object
..\..\..\..\go\src\github.com\redhat-cop\operator-utils\pkg\util\reconciler.go:98:42: cannot use runtimeObj (type "k8s.io/apimachinery/pkg/runtime".Object) as type "sigs.k8s.io/controller-runtime/vendor/k8s.io/apimachinery/pkg/runtime".Object in argument to r.GetClient().Update:
	"k8s.io/apimachinery/pkg/runtime".Object does not implement "sigs.k8s.io/controller-runtime/vendor/k8s.io/apimachinery/pkg/runtime".Object (wrong type for DeepCopyObject method)
		have DeepCopyObject() "k8s.io/apimachinery/pkg/runtime".Object
		want DeepCopyObject() "sigs.k8s.io/controller-runtime/vendor/k8s.io/apimachinery/pkg/runtime".Object
..\..\..\..\go\src\github.com\redhat-cop\operator-utils\pkg\util\reconciler.go:127:42: cannot use runtimeObj (type "k8s.io/apimachinery/pkg/runtime".Object) as type "sigs.k8s.io/controller-runtime/vendor/k8s.io/apimachinery/pkg/runtime".Object in argument to r.GetClient().Delete:
	"k8s.io/apimachinery/pkg/runtime".Object does not implement "sigs.k8s.io/controller-runtime/vendor/k8s.io/apimachinery/pkg/runtime".Object (wrong type for DeepCopyObject method)
		have DeepCopyObject() "k8s.io/apimachinery/pkg/runtime".Object
		want DeepCopyObject() "sigs.k8s.io/controller-runtime/vendor/k8s.io/apimachinery/pkg/runtime".Object
..\..\..\..\go\src\github.com\redhat-cop\operator-utils\pkg\util\reconciler.go:156:44: cannot use owner (type "k8s.io/apimachinery/pkg/apis/meta/v1".Object) as type "sigs.k8s.io/controller-runtime/vendor/k8s.io/apimachinery/pkg/apis/meta/v1".Object in argument to controllerutil.SetControllerReference:
	"k8s.io/apimachinery/pkg/apis/meta/v1".Object does not implement "sigs.k8s.io/controller-runtime/vendor/k8s.io/apimachinery/pkg/apis/meta/v1".Object (wrong type for GetCreationTimestamp method)
		have GetCreationTimestamp() "k8s.io/apimachinery/pkg/apis/meta/v1".Time
		want GetCreationTimestamp() "sigs.k8s.io/controller-runtime/vendor/k8s.io/apimachinery/pkg/apis/meta/v1".Time
..\..\..\..\go\src\github.com\redhat-cop\operator-utils\pkg\util\reconciler.go:156:44: cannot use obj (type "k8s.io/apimachinery/pkg/apis/meta/v1".Object) as type "sigs.k8s.io/controller-runtime/vendor/k8s.io/apimachinery/pkg/apis/meta/v1".Object in argument to controllerutil.SetControllerReference:
	"k8s.io/apimachinery/pkg/apis/meta/v1".Object does not implement "sigs.k8s.io/controller-runtime/vendor/k8s.io/apimachinery/pkg/apis/meta/v1".Object (wrong type for GetCreationTimestamp method)
		have GetCreationTimestamp() "k8s.io/apimachinery/pkg/apis/meta/v1".Time
		want GetCreationTimestamp() "sigs.k8s.io/controller-runtime/vendor/k8s.io/apimachinery/pkg/apis/meta/v1".Time
..\..\..\..\go\src\github.com\redhat-cop\operator-utils\pkg\util\reconciler.go:156:44: too many errors

**Comment by raffaelespazzoli** [comment]
did you run `make dep`?

**Comment by raffaelespazzoli** [comment]
@Snakesms are you still seeing the error? Can I close this?

**Comment by Snakesms** [comment]
@raffaelespazzoli 
Sorry for delayed reply.
After few iterations of dep init, dep ensure and go get I've finally managed to build it and deployed.

I didn't have a chance to spend enough time on tuning the app itself to let it run smoothly but so far I have few following questions if you will:

1) In deployment -> rolbinding you are binding SA to the Role "namespace-configuration-operator" &
   ClusterRole "admin"
a) Is it really necessary to give such a huge permissions like clusteradmin to the app? sounds very scary
b) If by any chance this level of permissions could be given - why we need to maintain additional role with restricted access?
2) What is the oldest OC version this app was tested on?
    I did try on 3.10 and it doesn't work properly due to mismatch between CRD definition and how OC cluster maintain CR (status section specifically)

**Comment by raffaelespazzoli** [comment]
@Snakesms 
I gave huge permissions on purpose to the service account. I am not sure it's the right thing to do, but it was necessary to be sure that the operator worked all the time because I don't know what resource the user will want to create.
It should be possible to narrow down the permission to just what you need (assuming you know what it is). I haven't tested the operator with restricted permission, it might just work but it will probably spit a bunch of errors in the log.
We could change the design of this operator to only work on a predefined set of resources that are passed for example as parameters. Right now it works on all the namespace-scoped resource types defined in the cluster. Let me know what you think of this.

I tested this operator with `oc` version 3.11 and higher.

**Comment by jeffspahr** [comment]
I'm running into the same issue:

```
$ make
go generate ./pkg/... ./cmd/...
go fmt ./pkg/... ./cmd/...
go vet ./pkg/... ./cmd/...
# github.com/redhat-cop/namespace-configuration-operator/pkg/apis/redhatcop/v1alpha1
../../src/github.com/redhat-cop/namespace-configuration-operator/pkg/apis/redhatcop/v1alpha1/register.go:18:19: undefined: scheme.Builder
# _/Users/jspahr/repo/namespace-configuration-operator/pkg/apis/redhatcop/v1alpha1
pkg/apis/redhatcop/v1alpha1/register.go:18:19: undefined: scheme.Builder
make: *** [vet] Error 2
```

I attempted `make dep`, but there's no `dep` option in the makefile.

**Comment by raffaelespazzoli** [comment]
@jeffspahr sorry my instructions were not accurate.
just run `dep ensure` , this should download the dependencies and let you get started.
