### ISSUE TITLE
Cannot test this because impersonation is not working

### ISSUE THREAD

**Issue by ahmedwaleedmalik** [redhat-cop/namespace-configuration-operator#43]
I cannot test the workflow since impersonation is not working. I can see that it is mentioned in the documentation [here](https://github.com/redhat-cop/namespace-configuration-operator/blob/master/examples/team-onboarding/readme.md#create-users-and-groups) as well. But is there any other way to test stuff out ? 

Also, I think until the ticket [MSTR-1000](https://issues.redhat.com/browse/MSTR-1000) (which is either deleted or is private) is resolved we should keep this issue open.

**Comment by raffaelespazzoli** [comment]
@ahmedwaleedmalik if you can setup a real IDP provider with OCP, then you don't have to impersonate users, you can simply login as that user to test. Impersonation is needed in the artificial scenario of the example where we can't make any assumption on the IDP provider.

**Comment by ahmedwaleedmalik** [comment]
Yup, that makes sense.
