### ISSUE TITLE
[FEATURE] Request for upgrade feature or doc

### ISSUE THREAD

**Issue by saberkan** [redhat-cop/namespace-configuration-operator#53]
Issue:
We are trying to find the best approach to upgrade the configurator. While CRD may have some changes, we need to find an approach to upgrade existing CRs without deleting them.

Expected:
An official procedure to upgrade the operator in a stable manner (without deleting existing CRs and CRDs).

**Comment by raffaelespazzoli** [comment]
can you test this approach:
1. turn off the old version operator (scale to zero). 
2. delete the CRs
3. update the CRDs
4. create the new CRs equivalent to the old ones
5. deploy the new operator
6. delete the old operator

If it works as expected we can document it.

**Comment by saberkan** [comment]
The procedure was applied successfully, meanwhile in step 4. we needed to delete existing CRDs, and recreate them, otherwise the following error occurs:
$ oc apply -f deploy/crds/redhatcop.redhat.io_namespaceconfigs_crd.yaml 
Warning: oc apply should be used on resource created by either oc create --save-config or oc apply
The CustomResourceDefinition "namespaceconfigs.redhatcop.redhat.io" is invalid: spec.scope: Invalid value: "Cluster": field is immutable
