### ISSUE TITLE
OperatorHub Packaging - Support Disconnected Environment Deployment

### ISSUE THREAD

**Issue by rguilme1** [redhat-cop/namespace-configuration-operator#69]
Please consider packaging the OperatorHub deployment of this operator to use the image sha256 digest notation instead of a version tag so that installations that are offline and utilize mirror registries will be able to deploy this operator and have the image pulled from the mirror for the quay.io registry.   OCP does not support tags with mirror registries.

This is important for secure environments that do not have direct internet access and utilize OCP mirror registries.

**Comment by bonkstok** [comment]
We had / have the same issue. 
It would indeed be very nice if the hash is used rather than the tag (also what Red Hat suggests).

As a workaround you can edit the csv and change the image to for example your on-prem registry or use the hash there :)

**Comment by raffaelespazzoli** [comment]
closed by #116
