### ISSUE TITLE
NamespaceConfig CR is not deleted automatically because of finalizer

### ISSUE THREAD

**Issue by cuttingedge1109** [redhat-cop/namespace-configuration-operator#89]
I am using namespaceconfig CR to create secrets and groups in the specific namespaces. It works well when create.
But when I try to delete, it hangs up and I need to remove finalizer in the manifest manually to perform deletion finally.
I checked the operator logs and found the followings:
```
  NamespaceConfig.redhatcop.redhat.io "nordmart-build-namespace-config" is
        invalid: metadata.finalizers: Forbidden: no new finalizers can be added
        if the object is being deleted, found new finalizers
        []string{"namespaceconfig-controller"}
```

**Comment by raffaelespazzoli** [comment]
@cuttingedge1109 thanks for letting us know. @cnuland would you be able to test this? It looks like a possible regression.

**Comment by cnuland** [comment]
@cuttingedge1109 we will need the full NamespaceConfig CR for reference to resolve

**Comment by cnuland** [comment]
Closing this since for lack of activity, please feel free to reopen if the issue persists
