### ISSUE TITLE
Issues Upgrading from v0.2.5 to v1+ using helmsman

### ISSUE THREAD

**Issue by hunguyenptc** [redhat-cop/namespace-configuration-operator#95]
We used helmsman dsf to install v0.2.5 onto our kubernetes cluster. When trying to update the version to 1.0.0 or greater, the following error is seen:

> {"level":"info","ts":1617378412.416105,"logger":"handler","msg":"2021-04-02 15:46:50 NOTICE: Upgrade release [ namespace-configuration-operator ] to version [ 1.0.2 ] in namespace [ namespace-configuration-operator ]"}
> {"level":"info","ts":1617378412.4161117,"logger":"handler","msg":"2021-04-02 15:46:52 ERROR: command for release [namespace-configuration-operator] returned [ 1 ] exit code and error message [ Error: UPGRADE FAILED: cannot patch \"namespace-configuration-operator\" with kind Deployment: Deployment.apps \"namespace-configuration-operator\" is invalid: spec.selector: Invalid value: v1.LabelSelector{MatchLabels:map[string]string{\"app.kubernetes.io/instance\":\"namespace-configuration-operator\", \"app.kubernetes.io/name\":\"namespace-configuration-operator\"}, MatchExpressions:[]v1.LabelSelectorRequirement(nil)}: field is immutable ]"}
> {"level":"info","ts":1617378412.4161308,"logger":"handler","msg":"2021-04-02 15:46:52 CRITICAL: Plan execution failed"}

Are there any doc on the breaking changes and/or upgrade procedure we should follow to upgrade from a 0.x version to 1.x version?

Thanks

**Comment by cnuland** [comment]
@hunguyenptc we don't have any document around this for this type of helm update, you will likely need to backup your CR files and reinstall fresh from 1.x
